### PR TITLE
Makefile: allow for verbose output with make V=1

### PR DESCRIPTION
**Pull request by rofl0r**
the same should be done for klystron, if the PR is accepted.
i have several more fixes in mind and would like to discuss them.
but not on discord.
i'll be idling in `#klystrack` on `irc.freenode.net` for a couple days in case you're interested.

### CODE REVIEW

**Comment by rofl0r** [comment]
i forgot to mention, the V=1 syntax is what's used by the linux kernel and almost all projects i'm aware of that use a plain makefile based build system. some use VERBOSE=1 for the same purpose.

**Comment by kometbomb** [comment]
Fair enough. This seems useful.

rofl0r <notifications@github.com> kirjoitti ti 5. helmikuuta 2019 klo 22.38:

**Comment by rofl0r** [comment]
thanks for merge. i'm around now in case you want to discuss the other things i mentioned.

**Comment by kometbomb** [comment]
Yeah we should split the changes into smaller tasks. Feel free to make PR's
if you have some clear fixes like the version number dependency issue.

rofl0r <notifications@github.com> kirjoitti la 9. helmikuuta 2019 klo 21.26:

**Comment by rofl0r** [comment]
i was thinking about factoring out some common functionality into a .mak snippet which could be stored in the klystron directory, so both projects could access it.

what do you think about the removal of the dependency generation i mentioned ?

**Comment by kometbomb** [comment]
Anything that you know makes the makefile work better and also cleaner I am happy to have PR's about. :) I think the only requirement from my side is to have a cleaner build process for the different platforms.

**Comment by kometbomb** [comment]
BTW, I think one critical issue is making the version number thing work better. The whole file creation could be eliminated and we could just set the version number in a define.

    gcc -DVERSION=`git describe --tags` ....

**Pull request merged**
